# Generated by Django 5.1.4 on 2026-06-24 20:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("channel", models.CharField(choices=[("whatsapp", "WhatsApp"), ("email", "Email")], max_length=20)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("checkout_approved", "Checkout Approved"),
                            ("checkout_denied", "Checkout Denied"),
                            ("installment_due", "Installment Due"),
                            ("installment_overdue", "Installment Overdue"),
                            ("installment_paid", "Installment Paid"),
                            ("limit_suspended", "Limit Suspended"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("provider_id", models.CharField(blank=True, max_length=100)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["customer", "event_type"], name="notificatio_custome_d5d3cd_idx"),
                    models.Index(fields=["status", "created_at"], name="notificatio_status_dee16f_idx"),
                ],
            },
        ),
    ]
