"""Celcoin integration stubs for Pix QR generation and payment confirmation."""

import logging
import uuid
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from typing import Any

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class PixChargeResult:
    celcoin_id: str
    txid: str
    qr_code: str
    pix_code: str
    expires_at: datetime


class CelcoinClient:
    """Stub client. Replace with real HTTP calls when credentials are available."""

    def create_dynamic_qr(self, amount_cents: int, description: str = "Pagamento Pagaê") -> PixChargeResult:
        """Generate a dynamic Pix QR code for the given amount."""
        txid = str(uuid.uuid4()).replace("-", "")[:35]
        celcoin_id = f"CEL-{uuid.uuid4().hex[:16].upper()}"
        # Real EMV payload would be generated by Celcoin; here we return a stub.
        qr_code = f"00020126430014BR.GOV.BCB.PIX0117{celcoin_id}520400005303986540{amount_cents:010d}5802BR5910Pagaê6009SaoPaulo"
        pix_code = f"pix:{celcoin_id}"
        expires_at = datetime.now(UTC) + timedelta(minutes=30)
        logger.info(
            "celcoin_qr_created",
            extra={"celcoin_id": celcoin_id, "txid": txid, "amount_cents": amount_cents},
        )
        return PixChargeResult(
            celcoin_id=celcoin_id,
            txid=txid,
            qr_code=qr_code,
            pix_code=pix_code,
            expires_at=expires_at,
        )

    def parse_payment_webhook(self, payload: dict[str, Any]) -> dict[str, Any] | None:
        """Parse and validate a Celcoin Pix payment webhook payload."""
        txid = payload.get("txid") or payload.get("endToEndId")
        if not txid:
            return None
        return {
            "txid": txid,
            "amount_cents": int(payload.get("amount", 0) * 100),
            "paid_at": payload.get("paidAt"),
            "payer_name": payload.get("payer", {}).get("name", ""),
            "payer_cpf": payload.get("payer", {}).get("cpf", ""),
            "status": "paid",
        }

    def outbound_pix(self, pix_key: str, amount_cents: int, description: str) -> dict[str, Any]:
        """Stub for merchant settlement via Pix transfer."""
        if not pix_key:
            return {"status": "failed", "failure_reason": "missing_pix_key"}
        e2e_id = f"E2E{uuid.uuid4().hex[:16].upper()}"
        logger.info(
            "celcoin_outbound_pix",
            extra={"pix_key": pix_key, "amount_cents": amount_cents, "e2e_id": e2e_id},
        )
        return {"e2e_id": e2e_id, "status": "completed"}
