# Generated by Django 5.1.4 on 2026-06-23 14:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("checkout", "0002_initial"),
        ("merchants", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.CharField(
                        choices=[
                            ("receivable", "Receivable"),
                            ("merchant_payable", "Merchant Payable"),
                            ("mdr_revenue", "MDR Revenue"),
                            ("cash", "Cash"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("description", models.CharField(max_length=255)),
                ("reference", models.CharField(blank=True, max_length=255)),
                (
                    "checkout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="checkout.checkoutsession",
                    ),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="payments.installment",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ledger Entry",
                "verbose_name_plural": "Ledger Entries",
                "db_table": "ledger_entries",
                "ordering": ["-created_at"],
            },
        ),
    ]
