# Generated by Django 5.1.4 on 2026-06-30 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('webhooks.webhookdelivery',),
        ),
    ]
