# Generated by Django 5.1.4 on 2026-06-22 22:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cpf", models.CharField(db_index=True, max_length=14, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("cep", models.CharField(blank=True, max_length=9)),
                ("street", models.CharField(blank=True, max_length=255)),
                ("number", models.CharField(blank=True, max_length=20)),
                ("complement", models.CharField(blank=True, max_length=100)),
                ("neighborhood", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=2)),
                (
                    "kyc_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("manual_review", "Manual Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("kyc_provider_id", models.CharField(blank=True, max_length=100)),
                ("kyc_approved_at", models.DateTimeField(blank=True, null=True)),
                ("serasa_score", models.SmallIntegerField(blank=True, null=True)),
                (
                    "risk_tier",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("approved_limit", models.IntegerField(default=0)),
                ("used_limit", models.IntegerField(default=0)),
                ("is_blocked", models.BooleanField(default=False)),
                ("blocked_reason", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "customers",
                "ordering": ["-created_at"],
            },
        ),
    ]
