# Generated by Django 5.1.4 on 2026-06-30 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantSettlement',
            fields=[
            ],
            options={
                'verbose_name': 'Merchant Settlement',
                'verbose_name_plural': 'Merchant Settlements',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('settlements.settlement',),
        ),
    ]
