# Generated by Django 5.1.4 on 2026-06-23 12:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("checkout", "0001_initial"),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Installment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.SmallIntegerField()),
                ("amount", models.IntegerField()),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("days_past_due", models.SmallIntegerField(default=0)),
                (
                    "checkout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="checkout.checkoutsession",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installments",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Installment",
                "verbose_name_plural": "Installments",
                "db_table": "installments",
                "ordering": ["checkout", "number"],
                "unique_together": {("checkout", "number")},
            },
        ),
        migrations.CreateModel(
            name="PixCharge",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("celcoin_id", models.CharField(blank=True, max_length=100, unique=True)),
                ("txid", models.CharField(blank=True, max_length=35, unique=True)),
                ("amount", models.IntegerField()),
                ("qr_code", models.TextField()),
                ("pix_code", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paid", "Paid"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("payer_name", models.CharField(blank=True, max_length=255)),
                ("payer_cpf", models.CharField(blank=True, max_length=14)),
                (
                    "installment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pix_charges",
                        to="payments.installment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pix Charge",
                "verbose_name_plural": "Pix Charges",
                "db_table": "pix_charges",
                "ordering": ["-created_at"],
            },
        ),
    ]
