# Generated by Django 5.1.4 on 2026-06-22 22:24

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("legal_name", models.CharField(max_length=255)),
                ("trade_name", models.CharField(blank=True, max_length=255)),
                ("cnpj", models.CharField(db_index=True, max_length=18, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.CharField(blank=True, max_length=255)),
                ("bank_code", models.CharField(blank=True, max_length=10)),
                ("bank_agency", models.CharField(blank=True, max_length=10)),
                ("bank_account", models.CharField(blank=True, max_length=20)),
                ("bank_account_type", models.CharField(blank=True, max_length=10)),
                ("pix_key", models.CharField(blank=True, max_length=255)),
                ("mdr_rate", models.DecimalField(decimal_places=4, default=Decimal("0.0700"), max_digits=5)),
                ("settlement_days", models.SmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("terminated", "Terminated"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("webhook_url", models.CharField(blank=True, max_length=500)),
                ("webhook_secret", models.CharField(blank=True, max_length=64)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="merchant_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant",
                "verbose_name_plural": "Merchants",
                "db_table": "merchants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MerchantApiKey",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key_prefix", models.CharField(max_length=20)),
                ("key_hash", models.CharField(max_length=255)),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "environment",
                    models.CharField(
                        choices=[("sandbox", "Sandbox"), ("production", "Production")],
                        default="production",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="api_keys", to="merchants.merchant"
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "db_table": "merchant_api_keys",
                "ordering": ["-created_at"],
            },
        ),
    ]
