# Generated by Django 5.1.4 on 2026-06-23 12:45

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("merchant_order_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("total_amount", models.IntegerField()),
                ("mdr_amount", models.IntegerField()),
                ("net_amount", models.IntegerField()),
                ("installment_count", models.SmallIntegerField()),
                ("installment_amount", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("expired", "Expired"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("decision", models.CharField(blank=True, max_length=10)),
                ("denial_reason", models.CharField(blank=True, max_length=50)),
                ("serasa_score_at_decision", models.SmallIntegerField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkout_sessions",
                        to="customers.customer",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="checkout_sessions",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checkout Session",
                "verbose_name_plural": "Checkout Sessions",
                "db_table": "checkout_sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
