# Generated by Django 5.1.4 on 2026-06-23 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("checkout", "0001_initial"),
        ("settlements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutsession",
            name="settlement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkouts",
                to="settlements.settlement",
            ),
        ),
        migrations.AddIndex(
            model_name="checkoutsession",
            index=models.Index(fields=["merchant", "created_at"], name="idx_checkout_merchant_created"),
        ),
        migrations.AddIndex(
            model_name="checkoutsession",
            index=models.Index(fields=["customer", "created_at"], name="idx_checkout_customer_created"),
        ),
        migrations.AddIndex(
            model_name="checkoutsession",
            index=models.Index(fields=["merchant", "merchant_order_id"], name="idx_checkout_merchant_order"),
        ),
    ]
