# Generated by Django 5.1.4 on 2026-06-30 04:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_initial'),
        ('customers', '0001_initial'),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_order_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('total_amount', models.IntegerField()),
                ('installment_count', models.SmallIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('converted', 'Converted'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='checkoutsession',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_sessions', to='checkout.order'),
        ),
        migrations.CreateModel(
            name='RiskAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_amount', models.IntegerField()),
                ('decision', models.CharField(max_length=10)),
                ('reasons', models.JSONField(default=list)),
                ('score', models.SmallIntegerField(blank=True, null=True)),
                ('approved_limit', models.IntegerField(blank=True, null=True)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_analyses', to='checkout.checkoutsession')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_analyses', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Risk Analysis',
                'verbose_name_plural': 'Risk Analyses',
                'db_table': 'risk_analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
